language: generic
os: linux
dist: focal

# We need a newer docker version since our multi-stage build
# relies on old stages not leaking into the current stage
# see https://github.com/moby/moby/issues/35641
addons:
  apt:
    sources:
      - sourceline: 'deb https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable'
    packages:
      - docker-ce

services:
  - docker

before_script:
  - mkdir -p e2e_data/scientist-collection/
  - sudo chmod -R o+rwx e2e_data

script:
  - docker build -t qlever .
  - docker run -it --rm -v "$(pwd)/e2e_data:/app/e2e_data/" --entrypoint e2e/e2e.sh qlever

notifications:
  email:
    on_success: never
    on_failure: always
