name: Docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get install -y docker


      - name: prepare folders
        run:  mkdir -p e2e_data/scientist-collection/ && sudo chmod -R o+rwx e2e_data
      - name: docker build
        run: docker build -t qlever .
      - name: E2E in Docker
        run:  sudo docker run -it --rm -v "$(pwd)/e2e_data:/app/e2e_data/" --entrypoint e2e/e2e.sh qlever
